// Regenerates src/overlay/oneko.ts from assets/oneko-sheet.gif.
//
// The sheet is the classic 1989 NekoDA cat by Kenji Gotoh (public domain),
// as arranged in adryd325/oneko.js: an 8×4 grid of 32×32 tiles.
//
//   node scripts/gen-oneko.mjs   (requires ffmpeg on PATH)

import { execFileSync } from "node:child_process";
import fs from "node:fs";

const W = 256;
const TILE = 32;

execFileSync("ffmpeg", ["-y", "-loglevel", "error", "-i", "assets/oneko-sheet.gif", "-f", "rawvideo", "-pix_fmt", "rgba", "/tmp/oneko-gen.rgba"]);
const buf = fs.readFileSync("/tmp/oneko-gen.rgba");

function tile(col, row) {
  const lines = [];
  for (let y = 0; y < TILE; y++) {
    let line = "";
    for (let x = 0; x < TILE; x++) {
      const px = (row * TILE + y) * W + col * TILE + x;
      const a = buf[px * 4 + 3];
      if (a === 0) line += ".";
      else line += buf[px * 4] > 128 ? "w" : "k";
    }
    lines.push(line);
  }
  return lines;
}

// tile coordinates follow oneko.js spriteSets (background-position / -32)
const MAP = {
  idle: [3, 3],
  alert: [7, 3],
  scratch1: [5, 0],
  scratch2: [6, 0],
  scratch3: [7, 0],
  tired: [3, 2],
  sleep1: [2, 0],
  sleep2: [2, 1],
  runW1: [4, 2],
  runW2: [4, 3],
  runE1: [3, 0],
  runE2: [3, 1],
};

let out = `// GENERATED by scripts/gen-oneko.mjs — do not edit by hand.
//
// Art: the 1989 NekoDA cat by Kenji Gotoh, released into the public domain;
// sheet arrangement from adryd325/oneko.js. '.'=transparent 'w'=white 'k'=black.

export const ONEKO_TILE = 32;

export type OnekoPose =
${Object.keys(MAP).map((k) => `  | "${k}"`).join("\n")};

export const ONEKO: Record<OnekoPose, string[]> = {
`;
for (const [name, [c, r]] of Object.entries(MAP)) {
  out += `  ${name}: [\n`;
  for (const line of tile(c, r)) out += `    "${line}",\n`;
  out += `  ],\n`;
}
out += `};\n`;
fs.writeFileSync("src/overlay/oneko.ts", out);
console.log(`wrote src/overlay/oneko.ts (${Object.keys(MAP).length} poses)`);
